src/Entity/RendezVous.php
<?php

namespace App\Entity;

use App\Repository\RendezVousRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RendezVousRepository::class)
 */
class RendezVous
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $titre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $all_days;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $backroundColor;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $borderColor;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $textColor;

    /**
     * @ORM\OneToOne(targetEntity=Patient::class, cascade={"persist", "remove"})
     */
    private $patient;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAllDays(): ?bool
    {
        return $this->all_days;
    }

    public function setAllDays(bool $all_days): self
    {
        $this->all_days = $all_days;

        return $this;
    }

    public function getBackroundColor(): ?string
    {
        return $this->backroundColor;
    }

    public function setBackroundColor(string $backroundColor): self
    {
        $this->backroundColor = $backroundColor;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->borderColor;
    }

    public function setBorderColor(string $borderColor): self
    {
        $this->borderColor = $borderColor;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->textColor;
    }

    public function setTextColor(string $textColor): self
    {
        $this->textColor = $textColor;

        return $this;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): self
    {
        $this->patient = $patient;

        return $this;
    }
}

src/Form/RendezVousType.php
<?php

namespace App\Form;

use App\Entity\RendezVous;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RendezVousType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('patient')
            ->add('titre')
            ->add('start', DateTimeType::class,['date_widget'=>'single_text'])
            ->add('end', DateTimeType::class,['date_widget'=>'single_text'])
            ->add('description')
            ->add('all_days')
            ->add('backroundColor',	ColorType::class)
            ->add('borderColor',ColorType::class)
            ->add('textColor',ColorType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => RendezVous::class,
        ]);
    }
}

src/Controller/RendezVousController.php
<?php

namespace App\Controller;

use App\Entity\RendezVous;
use App\Form\RendezVousType;
use App\Repository\RendezVousRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/rendez/vous')]
class RendezVousController extends AbstractController
{
    #[Route('/', name: 'rendez_vous_index', methods: ['GET'])]
    public function index(RendezVousRepository $rendezVousRepository): Response
    {
        return $this->render('rendez_vous/index.html.twig', [
            'rendez_vouses' => $rendezVousRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'rendez_vous_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $rendezVou = new RendezVous();
        $form = $this->createForm(RendezVousType::class, $rendezVou);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($rendezVou);
            $entityManager->flush();

            return $this->redirectToRoute('rendez_vous_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rendez_vous/new.html.twig', [
            'rendez_vou' => $rendezVou,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'rendez_vous_show', methods: ['GET'])]
    public function show(RendezVous $rendezVou): Response
    {
        return $this->render('rendez_vous/show.html.twig', [
            'rendez_vou' => $rendezVou,
        ]);
    }

    #[Route('/{id}/edit', name: 'rendez_vous_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, RendezVous $rendezVou, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RendezVousType::class, $rendezVou);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('rendez_vous_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('rendez_vous/edit.html.twig', [
            'rendez_vou' => $rendezVou,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'rendez_vous_delete', methods: ['POST'])]
    public function delete(Request $request, RendezVous $rendezVou, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rendezVou->getId(), $request->request->get('_token'))) {
            $entityManager->remove($rendezVou);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rendez_vous_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/rendez_vous/_delete_form.html.twig
<form method="post" action="{{ path('rendez_vous_delete', {'id': rendez_vou.id}) }}" onsubmit="return confirm('Vous etes sur à supprimer !?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rendez_vou.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/rendez_vous/_form.html.twig
{%  form_theme form 'bootstrap_5_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary m-2">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/rendez_vous/edit.html.twig
{% extends 'template.html.twig' %}

{% block title %}Modifer Rendez-Vous{% endblock %}

{% block body %}
    <h1>Modifier Rendez-Vous</h1>
    <hr>

    {{ include('rendez_vous/_form.html.twig', {'button_label': 'Modifer'}) }}

    <button class="btn btn-success" style="margin-left: 90%"><a style="color: white; " href="{{ path('rendez_vous_index') }}">Retour</a> </button>

   {#  {{ include('rendez_vous/_delete_form.html.twig') }} #}
{% endblock %}

templates/rendez_vous/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}RendezVous index{% endblock %}

{% block body %}
    <h1>Liste des RendezVous</h1>
    <hr>
    <br>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Start</th>
                <th>End</th>
                <th>Description</th>
                <th>All_days</th>
                <th>BackroundColor</th>
                <th>BorderColor</th>
                <th>TextColor</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for rendez_vou in rendez_vouses %}
            <tr>
                <td>{{ rendez_vou.id }}</td>
                <td>{{ rendez_vou.titre }}</td>
                <td>{{ rendez_vou.start ? rendez_vou.start|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ rendez_vou.end ? rendez_vou.end|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ rendez_vou.description }}</td>
                <td>{{ rendez_vou.allDays ? 'Yes' : 'No' }}</td>
                <td>{{ rendez_vou.backroundColor }}</td>
                <td>{{ rendez_vou.borderColor }}</td>
                <td>{{ rendez_vou.textColor }}</td>
                <td>
                    <a href="{{ path('rendez_vous_edit', {'id': rendez_vou.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" style="color: orange" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                        </svg></a>
                    <a href="{{ path('rendez_vous_show', {'id': rendez_vou.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" style="color: dodgerblue" width="16" height="16" fill="currentColor" class="bi bi-exclamation-circle-fill" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                        </svg></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <button class="btn btn-success"><a href="{{ path('rendez_vous_new') }}" style="color: white">Create new</a></button>
{% endblock %}

templates/rendez_vous/new.html.twig
{% extends 'template.html.twig' %}

{% block title %}Nouveau Rendez-Vous{% endblock %}

{% block body %}
    <h1>Créer Rendez-Vous</h1>
    <hr>

    {{ include('rendez_vous/_form.html.twig') }}

    <button class="btn btn-success" style="margin-left: 90%"> <a href="{{ path('rendez_vous_index') }}" style="color: white">Retour</a></button>
{% endblock %}

templates/rendez_vous/show.html.twig
{% extends 'template.html.twig' %}

{% block title %}Rendez-Vous{% endblock %}

{% block body %}
    <h1>Rendez-Vous</h1>
<hr>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ rendez_vou.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ rendez_vou.titre }}</td>
            </tr>
            <tr>
                <th>Début</th>
                <td>{{ rendez_vou.start ? rendez_vou.start|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Fin</th>
                <td>{{ rendez_vou.end ? rendez_vou.end|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ rendez_vou.description }}</td>
            </tr>
            <tr>
                <th>Tout jour</th>
                <td>{{ rendez_vou.allDays ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>BackroundColor</th>
                <td>{{ rendez_vou.backroundColor }}</td>
            </tr>
            <tr>
                <th>BorderColor</th>
                <td>{{ rendez_vou.borderColor }}</td>
            </tr>
            <tr>
                <th>TextColor</th>
                <td>{{ rendez_vou.textColor }}</td>
            </tr>
        </tbody>
    </table>

    <button class="btn btn-success" style="margin-left: 93%"><a  style="color:white;" href="{{ path('rendez_vous_index') }}">Retour</a> </button>

  {#   <a href="{{ path('rendez_vous_edit', {'id': rendez_vou.id}) }}">Modifier</a>

    {{ include('rendez_vous/_delete_form.html.twig') }} #}
{% endblock %}